### ISSUE TITLE
Mismatch in SHA512 checksum for Neon.2.23.8.exe

### ISSUE THREAD

**Issue by TobiasJu** [CityOfZion/neon-wallet#2594]
**Wallet version or commit SHA:**
Neon.2.23.8.exe

**Environment:**
e.g.: Win 10 Home (64 bit) Version 1709 Build 16299.309

**Reproduction steps:**
e.g.:
1. start Windows CMD
2. enter: `certutil -hashfile Neon.2.23.8.exe SHA512`

This is the result:
```
certutil -hashfile Neon.2.23.8.exe SHA512
SHA512-Hash von Neon.2.23.8.exe:
51b320cf83e465d7c1aea8211602227bb5b41a7658f3a7db315ab5de36e478841d70ebf0231fb554d7cd7f5b019c449b9b1da90563f9c866371ba89561d915be
```

In the latest.yml the checksum is:
```
version: 2.23.8
files:
  - url: Neon.2.23.8.exe
    sha512: UbMgz4PkZdfBrqghFgIie7W0GnZY86fbMVq13jbkeIQdcOvwIx+1VNfNf1sBnESbmx2pBWP5yGY3G6iVYdkVvg==
    size: 119072424
path: Neon.2.23.8.exe
sha512: UbMgz4PkZdfBrqghFgIie7W0GnZY86fbMVq13jbkeIQdcOvwIx+1VNfNf1sBnESbmx2pBWP5yGY3G6iVYdkVvg==
releaseDate: '2023-11-10T22:27:00.161Z'
```

The mismatch is because you encode the hash in base64 but windows puts ist out in hexadecimal. You have the same string two times inside your .yml file. Why don't you use the base64 **and** the hexadecimal representation instead?

PS: Also the latest.yml is missing for the Neon.2.23.10.exe 

best regards!
